name: jackett

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/jackett.yaml'
      - 'jackett/**'
      - '!jackett/*.md'
  pull_request:
    paths:
      - '.github/workflows/jackett.yaml'
      - 'jackett/**'
      - '!jackett/*.md'
    types:
      - opened
      - reopened

env:
  REGISTRY_IMAGE: k8sathome/${{ github.workflow }}
  GOSS_SLEEP: 30

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          VERSION=$(cat ${{ github.workflow }}/.version)
          echo ::set-output name=version::${VERSION}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
          version: latest
          driver-opts: image=moby/buildkit:master

      - name: Set up goss/dgoss
        uses: e1himself/goss-installation-action
        with:
          version: 'v0.3.16'

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push
        if: github.ref != 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          build-args: VERSION=${{ steps.prep.outputs.version }}
          context: .
          file: ./${{ github.workflow }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            k8sathome/pull-request:${{github.event.number}}

      - name: Test image
        if: github.ref != 'refs/heads/main'
        env:
          GOSS_FILE: ${{ github.workflow }}/goss.yaml
        run: |
          dgoss run k8sathome/pull-request:${{github.event.number}}

      - name: Build and Push
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          build-args: VERSION=${{ steps.prep.outputs.version }}
          context: .
          file: ./${{ github.workflow }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY_IMAGE }}:latest
            ${{ env.REGISTRY_IMAGE }}:v${{ steps.prep.outputs.version }}
